version: "3"

services:
  mlflow:
    image: u6kapps/mlflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: mlflow server --host 0.0.0.0 --port 5000

networks:
  default:
    external:
      name: production
