name: build

on: push

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Dummy
        run: |
          raise "test"
      - name: Build
        run: |
          docker build .

      # Slack notification
      - name: Slack notification on success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: build
          SLACK_ICON_EMOJI: :cat:
          SLACK_TITLE: Build success
          SLACK_MESSAGE: Build success
          SLACK_COLOR: good
      - name: Slack notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: build
          SLACK_ICON_EMOJI: :scream_cat:
          SLACK_TITLE: Build failure
          SLACK_MESSAGE: Build failure
          SLACK_COLOR: danger
